export const commonCopy = {
  brand: 'whatmint',
  nav: {
    shop: '商城',
    community: '社区',
    wishlist: '心愿单',
    official: '官方',
    officialTitle: '官方管理',
    assets: '我的资产',
    appeals: '解绑申诉',
    account: '账户设置',
    logout: '退出登录',
    login: '登录',
  },
  states: {
    loading: '加载中...',
    loadingMore: '加载中...',
    saving: '保存中...',
    submitting: '提交中...',
    processing: '处理中...',
    resolving: '识别中...',
    empty: '暂无内容',
    noMore: '没有更多了',
  },
  actions: {
    continue: '继续',
    cancel: '取消',
    save: '保存',
    submit: '提交',
    back: '上一步',
    open: '打开',
    preview: '预览',
    copy: '复制',
    remove: '移除',
    retry: '重试',
  },
  content: {
    fallbackTitle: '当前内容',
    video: '视频',
    work: '作品',
    asset: '资产',
    collection: '内容',
    minted: '已铸造',
    item: '物品',
  },
  dateRange: {
    recent7: '近7天',
    recent30: '近30天',
    all: '全部',
  },
  filters: {
    allSeries: '全部系列',
    allIp: '全部IP',
  },
};
