export const communityCopy = {
  feed: {
    toasts: {
      likeLogin: '请先登录再点赞',
      favoriteLogin: '请先登录再喜欢',
      wishlistExists: (name: string, count: number) => `「${name}」已在心愿单，当前 ${count} 人已加入`,
      wishlistAdded: (name: string, count: number) => `已将「${name}」加入心愿单，当前 ${count} 人已加入`,
    },
    pull: {
      release: '释放刷新',
      pull: '下拉刷新',
    },
    searchPlaceholder: '搜索内容...',
    sort: {
      latest: '最新',
      hot: '热门',
    },
    filters: {
      allSeries: '全部系列',
      allIp: '全部IP',
      detailTitle: '查看详情',
    },
    infiniteFinished: '没有更多了',
    empty: {
      filteredIcon: '🎬',
      filtered: '还未发售，期待一下',
      allIcon: '🐶',
      all: '还没有内容，小狗们正在路上...',
      action: '去上传第一个作品',
    },
    footer: {
      brand: 'whatmint',
      line: '碰一下，感受到了吗',
    },
    fallbackIp: 'IP',
  },
  ipDetail: {
    defaults: {
      tags: ['情绪应用', '实体入口', '可绑定资产'],
      story: '这个 IP 的档案还在补全中。它的核心不是一件商品，而是一个可以被触碰、被收藏、被再次回到的小世界。',
      series: '未归档系列',
      designer: 'WhatMint Studio',
      material: '实体载体 + NFC 芯片',
      size: '以实物为准',
      rarity: '常规发售',
      eyebrow: 'WhatMint IP',
      description: '一个可以通过实体触碰进入的小世界。购买在外部完成，WhatMint 负责内容、绑定和资产关系。',
      price: '外部渠道发售',
      registry: '开放登记',
      ip: 'IP',
    },
    specs: {
      series: '系列',
      designer: '设计',
      material: '材质',
      size: '尺寸',
      rarity: '稀有度',
    },
    status: {
      purchasable: (count: number) => `可购买，剩余 ${count}`,
      crowdfunding: (count: number, goal: number) => `众筹中 ${count}/${goal}`,
      success: '众筹成功',
      failed: '众筹已结束',
      unavailable: '暂不可购买',
    },
    toasts: {
      purchaseExternal: (name: string) => `购买「${name}」请前往外部渠道；收到 token 后在“我的资产”绑定。`,
      pledgeLogin: '请先登录后再参与众筹',
      pledgeSuccess: '已记录你的众筹意向',
      pledgeFailed: '众筹登记失败',
      wishlistExists: (name: string, count: number) => `「${name}」已在心愿单，目前 ${count} 人想要`,
      wishlistAdded: (count: number) => `已加入心愿单，目前 ${count} 人想要`,
    },
    labels: {
      limited: (count: number) => `限量 ${count}`,
      issued: (count: number, total: number) => `已发放 ${count} / ${total}`,
      crowdfunding: (count: number, goal: number) => `众筹 ${count} / ${goal}`,
    },
    actions: {
      purchase: '外部购买',
      pledged: '已登记众筹',
      pledge: '参与众筹',
      unavailable: '暂不可购买',
      bindAssets: '去我的资产绑定 token',
      wished: '已在心愿单',
      wish: '加入心愿单',
    },
    panels: {
      storyKicker: 'IP Story',
      storyTitle: '小世界档案',
      productKicker: 'Product Info',
      productTitle: '产品信息',
      contentKicker: 'Content Preview',
      contentTitle: '官方内容预览',
      contentIntro: '购买后写入的是 token 链接，内容可以继续更新，实体仍然是那个实体。',
      emptyContent: '这个 IP 暂无公开内容，后续可在官方管理端补充预览。',
    },
  },
};
