// Shared user-facing copy: global labels, generic actions, and cross-page UI terms.
export const commonCopy = {
  brand: 'whatmint',
  nav: {
    home: '首页',
    shop: '商城',
    studio: 'Mint Studio',
    official: '官方',
    officialTitle: '官方管理',
    assets: 'Mint Space',
    appeals: '解绑申诉',
    account: '账户设置',
    logout: '退出登录',
    login: '登录',
    openMenu: '打开导航',
    closeMenu: '关闭导航',
  },
  states: {
    loading: '加载中...',
    loadingMore: '加载中...',
    saving: '保存中...',
    submitting: '提交中...',
    processing: '处理中...',
    resolving: '识别中...',
    empty: '暂无内容',
    noMore: '没有更多了',
  },
  errors: {
    invalidJson: '服务返回格式异常，请稍后再试',
    requestFailed: (status: number) => `请求失败，请稍后再试（${status}）`,
  },
  actions: {
    continue: '继续',
    cancel: '取消',
    save: '保存',
    submit: '提交',
    back: '上一步',
    open: '打开',
    preview: '预览',
    copy: '复制',
    remove: '移除',
    retry: '重试',
    close: '关闭',
  },
  content: {
    fallbackTitle: '当前内容',
    video: '视频',
    work: '作品',
    asset: '内容资产',
    collection: '内容',
    minted: '已铸造',
    item: '物品',
  },
  dateRange: {
    recent7: '近7天',
    recent30: '近30天',
    all: '全部',
  },
  filters: {
    allSeries: '全部系列',
    allIp: '全部IP',
  },
};
