export const contentCopy = {
  blocks: {
    actionTitle: '小动作',
    audioTitle: '音频',
    linkLabel: '打开链接',
    unsupportedVideo: '当前浏览器暂不支持这个视频格式',
    openVideo: '打开视频',
  },
  detail: {
    toasts: {
      likeLogin: '请先登录或注册后再点赞',
      favoriteLogin: '请先登录或注册后再收藏',
      previewCopied: '预览链接已复制',
      bindLogin: '请先登录或注册，再到“我的资产”绑定实体并设置默认内容',
      contentIdCopied: '内容 ID 已复制',
      defaultUpdated: '实体默认内容已更新',
      downloading: '视频下载中...',
      promptCopied: '提示词已复制',
    },
    tokenBind: {
      empty: '请输入实体 token',
      success: '已写入实体，碰一下就会优先播放这条内容',
      failed: '绑定失败，请确认 token 是否正确',
      kicker: 'Token',
      title: '直接写入实体',
      body: '如果实体还没有绑定账号，可以输入 token，把当前内容直接设为它的默认播放内容。',
      placeholder: '输入实体 token',
      writing: '写入中...',
      write: '写入',
    },
    meta: {
      series: (name: string) => `系列 · ${name}`,
      ip: (name: string) => `IP · ${name}`,
      id: (id: string) => `内容 ID：${id}`,
    },
    actions: {
      sharePreview: '分享预览',
      bindEntity: '绑定到实体',
      bindHint: '点击“绑定到实体”会跳转到我的资产，并把当前内容作为默认内容候选带过去。',
      back: '返回',
    },
    remix: {
      title: '二创 · 换成你家的宠物',
      desc: '把参考视频下载给 AI 视频工具，再复制提示词，就可以尝试生成自己的宠物版本。',
      downloadTitle: '下载参考视频',
      downloadBody: '作为动作、场景和运镜参考上传给 AI。',
      downloadAction: '下载视频',
      promptTitle: '复制提示词',
      promptBody: '粘贴给 AI 视频工具，配合你的宠物图片使用。',
      promptAction: '复制提示词',
      copied: '已复制',
      toolTitle: '打开生成工具',
      toolBody: '上传视频、图片和提示词，生成二创版本。',
      toolAction: '打开豆包视频生成',
      prompt: (title: string) => `请基于参考视频，将视频中的小狗替换为我上传的宠物图片中的角色。要求：1）保持原视频动作、场景和运镜不变；2）替换角色需要自然融合；3）输出相同时长和比例的视频。参考视频标题：「${title}」`,
    },
  },
  player: {
    defaultSet: '已设为默认',
    ownerLoginRequired: '已绑定实体需登录对应账号修改',
    defaultFailed: '设置默认失败',
    error: {
      title: '无法加载内容',
      hint: '链接可能已失效或内容暂不可用',
      community: '去社区看看',
      shop: '去商城看看',
    },
    sound: '点击开启声音',
    ad: {
      brand: 'whatmint',
      title: '发现更多精彩内容',
      desc: '社区里有更多创作者的情绪表达',
      community: '进入社区',
      shop: '进入商城',
      dismiss: '继续浏览',
    },
  },
  remixModal: {
    alert: '二创功能即将上线，敬请期待！',
    title: '二创 · 换成你的角色',
    desc: '上传一张你的角色图片，AI 将生成一段以你的角色为主角的视频。',
    sourceLabel: '原始视频',
    uploadIcon: '🐕',
    uploadText: '上传你的角色图片',
    uploadHint: '支持 PNG/JPG，建议正面透明背景',
    change: '点击更换',
    submit: '生成二创视频',
    notice: '功能即将上线，当前仅预览界面',
  },
};
