// Content detail copy: content asset viewing, preview, binding, edit, delete, and related error text.
export const contentCopy = {
  blocks: {
    actionTitle: '小动作',
    audioTitle: '音频',
    linkLabel: '打开链接',
    unsupportedVideo: '当前浏览器暂不支持这个视频格式',
    openVideo: '打开视频',
  },
  detail: {
    toasts: {
      previewCopied: '预览链接已复制',
      bindLogin: '请先登录或注册，再到 Mint Space 接入物件并设置默认内容',
      contentIdCopied: '内容 ID 已复制',
      defaultUpdated: '物件默认内容已更新',
      downloading: '视频下载中...',
      promptCopied: '提示词已复制',
      editLogin: '请先登录后再修改内容',
      deleteSuccess: '内容资产已删除',
    },
    states: {
      emptyRenderable: '暂无可渲染内容。',
    },
    tokenBind: {
      empty: '请输入物件 token',
      success: '已写入物件，触碰时会优先打开这条内容',
      failed: '绑定失败，请确认 token 是否正确',
      kicker: 'Token',
      title: '直接写入物件',
      body: '如果物件还没有绑定账号，可以输入 token，把当前内容直接设为它的默认内容。',
      placeholder: '输入物件 token',
      writing: '写入中...',
      write: '写入',
    },
    meta: {
      series: (name: string) => `系列 · ${name}`,
      ip: (name: string) => `IP · ${name}`,
      id: (id: string) => `内容 ID：${id}`,
    },
    actions: {
      preview: '预览',
      sharePreview: '分享预览',
      openExperience: '进入体验',
      bindIpInstance: '绑定到物件',
      bindAccountAsset: '绑定到实体 IP',
      bindHint: '点击“绑定到物件”会跳转到 Mint Space，并把当前内容作为默认内容候选带过去。',
      copyContentId: '复制内容 ID',
      revise: '编辑新版',
      replaceResource: '替换资源',
      manageTitle: '维护内容',
      manageHint: '进入创作中心替换资源，保留内容资产与实体绑定关系。',
      extend: '续写内容',
      delete: '删除内容',
      deleteTitle: '危险操作',
      deleteHint: '删除后内容会从内容中心移除，相关实体默认内容也会解除。',
      deleting: '删除中...',
      confirmDelete: (title: string) => `确认删除「${title || '这条内容'}」吗？删除后它会从内容中心移除，已绑定物件也会解除这条内容。`,
      back: '返回',
    },
    renderer: {
      title: '渲染方式',
      previewHint: '体验预览会按 OS 内容渲染协议打开，不等同于维护详情页。',
      videoFullscreen: '视频全屏播放',
      arCameraOverlay: 'AR 摄像头叠加',
      blocks: '内容块渲染',
      fallback: (renderer: string) => renderer || '默认渲染',
    },
    nodes: {
      title: '内容节点',
      empty: '还没有结构化内容节点。后续修改会围绕节点和资源进行。',
      unit: (index: number) => `节点 ${index}`,
      resourceCount: (count: number) => `${count} 个资源`,
    },
    maintenance: {
      kicker: '内容维护',
      untitled: '未命名内容',
      noCover: '暂无封面',
      resource: '资源',
      nodeSummary: (nodes: number, resources: number) => `${nodes} 个节点 · ${resources} 个资源`,
      resourceSummary: (resources: number) => `${resources} 个资源`,
    },
    entityBind: {
      eyebrow: '默认体验',
      title: '绑定到实体 IP',
      body: '输入实体 token，把这条内容设为该物件的默认体验；未绑定实体会同步进入当前账号。',
      placeholder: '输入实体 token',
      empty: '请输入实体 token',
      action: '写入实体',
      binding: '写入中...',
      success: '已写入实体 IP，触碰物件时会打开这条内容。',
      failed: '写入失败，请确认 token 是否正确或是否有权限。',
      defaultFailed: '默认内容写入失败，请稍后在资产页手动设置。',
    },
    versions: {
      current: (version: number) => `当前版本：v${version}`,
      draftCount: (count: number) => `有 ${count} 个草稿待发布`,
      editHint: '编辑会先进入创作中心生成新版草稿，确认后再发布。',
    },
    officialDefault: {
      title: '官方默认内容',
      body: '仅官方账号可见。设置后商城和官方示例会优先展示这条内容。',
      successHint: '已设为这个 IP 的官方默认内容，商品详情页会展示这条内容。',
      successToast: '官方默认内容已更新',
      failed: '设置官方默认内容失败',
      setting: '设置中...',
      set: '设为官方默认内容',
      setDone: '已设为官方默认内容',
    },
    error: {
      title: '无法加载内容',
      hint: '链接可能已失效，或内容暂时不可见。',
      back: '返回',
    },
    remix: {
      title: '二创 · 换成你家的宠物',
      desc: '把参考视频下载给 AI 视频工具，再复制提示词，就可以尝试生成自己的宠物版本。',
      downloadTitle: '下载参考视频',
      downloadBody: '作为动作、场景和运镜参考上传给 AI。',
      downloadAction: '下载视频',
      promptTitle: '复制提示词',
      promptBody: '粘贴给 AI 视频工具，配合你的宠物图片使用。',
      promptAction: '复制提示词',
      copied: '已复制',
      toolTitle: '打开生成工具',
      toolBody: '上传视频、图片和提示词，生成二创版本。',
      toolAction: '打开豆包视频生成',
      prompt: (title: string) => `请基于参考视频，将视频中的小狗替换为我上传的宠物图片中的角色。要求：1）保持原视频动作、场景和运镜不变；2）替换角色需要自然融合；3）输出相同时长和比例的视频。参考视频标题：「${title}」`,
    },
  },
  player: {
    osLabel: 'WhatMint OS Player',
    defaultTitle: 'WhatMint 内容',
    error: {
      title: '无法加载内容',
      hint: '链接可能已失效或内容暂不可用',
      shop: '去商城看看',
    },
    sound: '点击开启声音',
    replay: '再播放一次',
    ar: {
      osLabel: 'WhatMint OS AR',
      cameraFallback: '摄像头未开启，已进入 AR 平面预览',
      preparingTracking: '正在准备 AR 识别',
      scanningMarker: '请将镜头对准桌面秘境标记',
    },
  },
  remixModal: {
    alert: '二创功能即将上线，敬请期待！',
    title: '二创 · 换成你的角色',
    desc: '上传一张你的角色图片，AI 将生成一段以你的角色为主角的视频。',
    sourceLabel: '原始视频',
    uploadIcon: '🐕',
    uploadText: '上传你的角色图片',
    uploadHint: '支持 PNG/JPG，建议正面透明背景',
    change: '点击更换',
    submit: '生成二创视频',
    notice: '功能即将上线，当前仅预览界面',
  },
};
