// Shop module copy: public IP discovery, application introduction, experience preview, and external invitation entry.
export const shopCopy = {
  product: {
    defaultTags: ['情绪入口', 'NFC 实体', '现实 UI'],
    empty: '暂时还没有可以邀请的新存在',
    emptyFiltered: '暂时没有符合这些条件的存在，可以放宽筛选再看看。',
  },
  filters: {
    ariaLabel: '商城筛选',
    eyebrow: 'Discovery Filter',
    title: '按生活场景寻找入口',
    searchLabel: '关键词',
    searchPlaceholder: '搜索名字、性格、场景或故事线索',
    application: '应用',
    allApplications: '全部应用',
    tag: '气质',
    allTags: '全部气质',
    withExperience: '已有官方体验',
    withInvitation: '已有邀请入口',
    clear: '清空筛选',
    resultCount: (count: number, total: number) => `显示 ${count} / ${total} 个存在`,
  },
  toast: {
    externalPurchase: (name: string) => `「${name}」暂时通过外部渠道邀请；收到 token 后可回到 Mint Space 接入。`,
  },
  card: {
    defaultApp: '轻应用',
    fallbackDescription: '触碰实体即可进入对应的场景体验，内容可以更新，也可以成为长期存在的表达入口。',
    detail: '认识它',
    externalPurchase: '邀请方式',
  },
  detail: {
    loading: '正在打开这个存在的档案...',
    missing: '没有找到这个 IP',
    back: '回到商城',
    fallbackEyebrow: 'WhatMint IP',
    fallbackDescription: '它还在整理自己的介绍。',
    fallbackStory: '这个存在正在抵达 WhatMint。它会拥有自己的实体入口、应用体验和进入 Mint Space 的方式。',
    tagsFallback: ['可触碰', '可接入', '可体验'],
    invite: '了解邀请方式',
    inviteHint: '邀请通常发生在外部渠道；拿到 token 后，回到 Mint Space 接入实体。',
    experience: '体验官方示例',
    experienceEmpty: '官方示例内容还在准备中。',
    mintSpace: '去 Mint Space 接入',
    appTitle: '它会如何活着',
    appFallback: '这个应用会定义触碰后的交互、内容模板和体验节奏。',
    specTitle: '实体信息',
    storyTitle: '关于它',
    contentTitle: '官方体验',
    contentIntro: '这里展示用户在触碰实体或进入空间时会看到的默认体验。',
    specs: {
      series: '系列',
      creator: '创作者',
      material: '材质',
      size: '规格',
      nfc: 'NFC 类型',
      app: '应用',
    },
  },
};
