export const studioCopy = {
  initialMessage: '请给我物件码。',
  placeholders: {
    token: '输入物件码',
    newToken: '输入新的物件码',
    chooseStep: '选择当前步骤',
    continueInput: '继续输入',
    uploadWithFile: '按发送上传资源',
    uploadEmpty: '选择资源后发送',
  },
  messages: {
    previewFirst: '先预览当前内容。',
    ready: '已准备好。',
    tokenRequired: '请输入物件码。',
    resolveFailed: '识别失败。请重试。',
    recognized: (name: string) => `${name}已识别。`,
    backToToken: '请给我物件码。',
    backToChoice: '回到创作步骤。',
    backToStep: '回到上一步。',
    enterApp: '进入应用。',
    chooseResourceThenSend: '请选择资源，然后发送。',
    uploadFailed: '上传失败。',
    resourceUploaded: (label: string) => `${label}已上传。`,
    resourceRequired: '请先上传至少一组内容资源。',
    definitionContentCreated: '内容已经铸造完成。可以进入体验，也可以去详情页绑定实体 IP 或维护资源。',
    previewResourceRequired: '请先上传资源，再预览。',
    draftPreviewOpened: '已打开临时预览。确认后再完成铸造。',
    resourceLabel: '资源',
    confirmResourceFile: (label: string) => `确认${label}文件`,
    defaultUnitLabel: '第 {index} 段',
    uploadResourcePrompt: (unitLabel: string, index: number, label: string) => `${unitLabel.replace('{index}', String(index))}：上传${label}。`,
    definitionContentTitle: (name: string, contentTitle?: string) => contentTitle ? `${name} · ${contentTitle}` : `${name}的内容`,
    skip: '跳过',
    saveFailed: '保存失败。请重试。',
    contentDraftSaved: '新版草稿已保存。确认无误后可以发布。',
    contentDraftFailed: '新版草稿保存失败。请重试。',
    contentPublished: '新版内容已发布。',
    contentPublishFailed: '新版发布失败。请重试。',
    finishMint: '完成铸造',
    mintDone: '铸造完成。',
    mintDoneWithAsset: '铸造完成。需要的话，可以把它收进你的资产。',
    guideDone: '创作引导已完成。',
    collectAsset: '收藏资产',
    collectFailed: '收藏失败。',
    collected: '已收进你的资产。',
    bindContentToEntity: '绑定实体 IP',
    contentBoundToEntity: '已绑定到实体 IP。触碰物件时会打开这条内容。',
    contentBindFailed: '绑定实体 IP 失败。请稍后到内容详情页重试。',
  },
  toast: {
    done: '已完成',
    uploaded: '已上传',
    saved: '已保存',
    draftSaved: '草稿已保存',
    published: '已发布',
    minted: '铸造完成',
    collected: '已收藏',
    loggedIn: '已登录',
  },
  sidebar: {
    collapse: '收起侧边栏',
    newMintTitle: '开启新铸造',
    newMint: '新铸造',
    mintedTitle: '最近内容',
    loading: '加载内容中...',
    empty: '完成一次铸造后，它会留在这里。',
    close: '关闭侧边栏',
    search: '搜索内容',
    filterAll: '全部',
    noResults: '没有匹配的内容。',
    collapseList: '收起内容列表',
    expandList: '展开内容列表',
    moreCount: (count: number) => `还有 ${count} 个结果，搜索可继续收窄。`,
  },
  preview: {
    contentAsset: '内容资产',
    currentContent: '当前内容',
    openInNewPage: '新页预览',
    active: '已生效',
    uploaded: '已上传',
  },
  actions: {
    continue: '继续',
    finishMint: '完成铸造',
    publishVersion: '发布新版',
    previewNewPage: '新页预览',
    collectAsset: '绑定实体 IP',
    viewAsset: '查看资产',
    removeFile: '移除文件',
    back: '上一步',
    chooseResource: '选择资源',
    closeDetail: '关闭详情',
    deleteContent: '删除内容',
  },
  detail: {
    title: '内容详情',
    loading: '内容详情加载中...',
    preview: '进入体验',
    openDetail: '维护详情',
    deleteHint: '删除后不可恢复，请确认这是不再需要的内容。',
    confirmDelete: (title: string) => `确认删除「${title || '这条内容'}」？删除后不可恢复。`,
    deleteUnavailable: '这个内容暂不支持在 Studio 删除。',
    deleteSuccess: '内容已删除。',
  },
  libraryStatus: {
    content: '内容',
    draft: '草稿',
    processing: '处理中',
    published: '已发布',
  },
  defaultTitle: '当前内容',
};
