export const studioCopy = {
  initialMessage: '请给我物件码。',
  placeholders: {
    token: '输入物件码',
    newToken: '输入新的物件码',
    chooseStep: '选择当前步骤',
    continueInput: '继续输入',
    uploadWithFile: '按发送上传视频',
    uploadEmpty: '选择视频后发送',
    titleVideo: '给这段内容起个名字',
  },
  messages: {
    previewFirst: '先预览当前内容。',
    ready: '已准备好。',
    tokenRequired: '请输入物件码。',
    resolveFailed: '识别失败。请重试。',
    recognized: (name: string) => `${name}已识别。`,
    backToToken: '请给我物件码。',
    backToPreview: '回到预览。',
    backToChoice: '回到内容选择。',
    backToStep: '回到上一步。',
    chooseContent: '选择内容。',
    enterApp: '进入应用。',
    uploadVideo: '上传视频',
    chooseVideoThenSend: '请选择视频，然后发送。',
    useCurrentContent: '使用当前内容',
    currentSelected: '当前内容已选。',
    uploadFailed: '上传失败。',
    bindFailedAfterUpload: '内容已上传，但绑定失败。',
    customVideoReady: '专属视频已准备好。',
    videoUploaded: '视频已上传。',
    skip: '跳过',
    saveFailed: '保存失败。请重试。',
    momentSaved: '这一刻已保存。',
    finishMint: '完成铸造',
    mintDone: '铸造完成。',
    mintDoneWithAsset: '铸造完成。需要的话，可以把它收进你的资产。',
    collectAsset: '收藏资产',
    collectFailed: '收藏失败。',
    collected: '已收进你的资产。',
    reselectVideo: '可以重新选择视频。',
  },
  toast: {
    done: '已完成',
    uploaded: '已上传',
    saved: '已保存',
    minted: '铸造完成',
    collected: '已收藏',
    loggedIn: '已登录',
  },
  sidebar: {
    collapse: '收起侧边栏',
    newMintTitle: '开启新铸造',
    newMint: '新铸造',
    mintedTitle: '已铸造内容',
    loading: '加载内容中...',
    empty: '完成一次铸造后，它会留在这里。',
    close: '关闭侧边栏',
  },
  preview: {
    contentAsset: '内容资产',
    momentContent: '纪念内容',
    currentContent: '当前内容',
    openInNewPage: '新页预览',
    customContent: '专属内容',
    active: '已生效',
    uploaded: '已上传',
  },
  actions: {
    continue: '继续',
    useCurrent: '使用当前内容',
    keepOfficial: '保留官方预览',
    uploadVideo: '上传视频',
    customize: '定制专属内容',
    finishMint: '完成铸造',
    previewNewPage: '新页预览',
    collectAsset: '收藏资产',
    viewAsset: '查看资产',
    removeFile: '移除文件',
    back: '上一步',
    chooseVideo: '选择视频',
  },
  libraryStatus: {
    work: '作品',
    video: '视频',
    asset: '资产',
    collection: '内容',
    minted: '已铸造',
  },
  defaultTitle: '当前内容',
  customContentTitle: (name: string) => `${name}的专属内容`,
};
