// User domain copy: login/account/appeal plus Mint Space home, partner detail, token access, and asset-operation errors.
export const userCopy = {
  login: {
    title: 'whatmint',
    tabs: {
      login: '账户登录',
      register: '注册',
    },
    fields: {
      username: '用户名',
      password: '密码',
      confirmPassword: '确认密码',
    },
    actions: {
      login: '登录',
      loginLoading: '登录中...',
      register: '注册',
      registerLoading: '注册中...',
    },
    agreement: {
      prefix: '我已阅读并同意',
      disclaimer: '免责声明',
      and: '和',
      privacy: '隐私政策',
    },
    errors: {
      loginRequiredFields: '请填写用户名和密码',
      registerRequiredFields: '请填写所有字段',
      passwordMismatch: '两次密码不一致',
      passwordTooShort: '密码至少4位',
      loginFailed: '登录失败',
      registerFailed: '注册失败',
    },
  },
  account: {
    loginRequiredToast: '请先登录或注册后再进入账户设置',
    eyebrow: 'Account',
    title: '账户设置',
    intro: '这里只保留账号资料与安全设置；实体 IP 和伙伴入口已经拆到 Mint Space。',
    loading: '加载中...',
    creatorAccount: '创作者账号',
    normalAccount: '普通账号',
    password: {
      title: '修改密码',
      intro: '为了保护私有内容和实体管理权限，建议定期更新密码。',
      current: '当前密码',
      next: '新密码',
      confirm: '确认新密码',
      save: '保存新密码',
      required: '请填写所有密码字段',
      mismatch: '两次输入的新密码不一致',
      success: '密码修改成功',
      failed: '修改失败，请稍后再试',
    },
  },
  appeal: {
    eyebrow: 'Appeal',
    title: '订单号申诉解绑',
    intro: '如果 token 在运输中泄露并被抢先绑定，可在一个月内提交外部订单号，官方人工核验后处理解绑。',
    fields: {
      orderNo: '外部订单号',
      orderNoPlaceholder: '例如 WM20260713ABCD1234',
      token: 'token（可选）',
      tokenPlaceholder: '如果你手上有 token，可以一起提交',
      reason: '说明（可选）',
      reasonPlaceholder: '简单说明问题，例如 token 疑似运输途中泄露',
    },
    actions: {
      submit: '提交申诉',
      submitting: '提交中...',
    },
    messages: {
      orderRequired: '请输入外部订单号',
      submitted: '申诉已提交，官方会人工核验并处理解绑',
      toastSubmitted: '申诉已提交',
    },
  },
  assets: {
    galleryTypeEntity: '情绪 IP',
    unnamedIp: '未命名 IP',
    entityAsset: '实体 IP',
    officialDefault: '官方默认内容',
    waitingContent: '等待内容发布',
    tokenMissing: '未生成',
    toasts: {
      entityBoundDefaultSet: '实体已绑定，并写入当前内容为默认内容',
      entityBoundDefaultLater: '实体已绑定，默认内容需要稍后手动设置',
      unbound: '已解绑，token 可以重新绑定到其他账号',
      unbindFailed: '解绑失败',
      tokenCopied: 'token 已复制',
      transferTargetRequired: '请输入接收方账号',
      transferSuccess: '转赠成功',
      transferFailed: '转赠失败',
      contentIdRequired: '请输入内容 ID',
      defaultUpdated: '默认内容已更新',
      updateFailed: '更新失败',
      shareSaved: 'Mint Space 分享卡已保存',
      shareFailed: '暂时无法生成分享卡',
    },
    bind: {
      emptySmart: '请输入实体 token',
      entitySuccessSpace: '实体 IP 已接入你的 Mint Space',
      failed: '绑定失败，请确认 token 是否正确',
      entityEmpty: '请输入实体 token',
      entitySuccess: '实体绑定成功',
    },
    emptyGateway: {
      eyebrow: 'Mint Space Access',
      title: '这里正等第一位存在进来',
      body: '你的 Mint Space 还很安静。输入实体随附的 token，把第一位伙伴接入这里；它会带来这个空间最初的光线、温度和性格。',
      bind: '接入第一个存在',
      shop: '先去认识新的存在',
    },
    permissionRecovery: {
      title: '这个实体已经在别人的 Mint Space 里',
      body: '如果它原本属于你，可以先确认是否登录了正确账号；如果 token 疑似被抢先绑定，可以提交订单号申诉，由官方人工核验。',
      switchAccount: '换账号登录',
      appeal: '提交申诉',
    },
    transferWelcome: {
      title: '有一位新的存在进入了你的 Mint Space',
      body: '它是通过转赠来到这里的。你可以先看看它的当前体验，也可以稍后为它重新设置默认内容。',
      action: '我知道了',
    },
    hero: {
      eyebrow: 'Mint Space',
      title: '我的 Mint Space',
      intro: '这里是一张正在形成的世界名片。每个被邀请进来的实体 IP，都会改变这里的光线、天气和气质。',
      bindNew: '邀请新的存在',
      bindHint: '收到官方 token 后，从这里把实体 IP 接入你的 Mint Space。',
      openMint: '进入创作中心',
      openShop: '探索新的存在',
      countLabel: '位伙伴',
      countDetail: (entities: number) => `${entities} 位存在已进入这里`,
    },
    loginGuide: {
      title: '需要先登录或注册',
      body: '实体接入、默认内容修改和转赠都属于账号权限操作。请先登录，然后回到这里继续绑定。',
      tokenHint: '当前链接带有 token，登录后可重新打开链接，或复制 token 后在本页手动绑定。',
      backHome: '回到首页登录',
    },
    loading: '正在同步你的 IP 空间...',
    bindCard: {
      eyebrow: 'Access Token',
      title: '接入你的第一个存在',
      emptyTitle: '让第一位伙伴进入这里',
      intro: '输入实体随附的 token，让它进入你的 Mint Space。接入后，你可以管理默认体验、创作内容，也可以在需要时转赠或解绑。',
      emptyIntro: 'Mint Space 会从第一个实体 IP 开始成形。输入 token 后，它会成为这里的第一位伙伴。',
      placeholder: '输入实体 token',
      bindSpace: '接入 Mint Space',
      bindAndSetDefault: '接入并设为默认体验',
      entityOnly: '仅绑定实体 IP',
      close: '关闭接入面板',
    },
    defaultHint: {
      title: '已带入一个内容 ID',
      body: '绑定实体后，可以在 IP 空间管理卡里一键把它设为默认体验。',
    },
    emptySpace: {
      title: 'Mint Space 还没有被点亮',
      body: '如果你已经拿到实体 token，可以先把它接进来；如果还没有，也可以先让这里保持一会儿安静。',
      bind: '接入 token',
    },
    space: {
      application: (name: string) => `轻应用 · ${name}`,
      experience: '进入体验',
      create: '创作内容',
      manage: '管理',
    },
    mintSpace: {
      title: '我的 Mint Space',
      emptySummary: '邀请第一个存在进入这里之后，你的 Mint Space 会开始拥有自己的气质。',
      emptySubtitle: '等待第一次相遇',
      emptyDescription: '这里还保持着安静的空白。第一位进入的存在，会像一盏小灯，决定这里最初的温度和方向。',
      emptyTrait: '未被点亮',
      emptyNotes: [
        { id: 'empty-world-1', text: '每个 Mint Space 一开始都很安静，像一间刚刚打开窗的房间。', source: 'copy' },
        { id: 'empty-world-2', text: '还没有伙伴住进来之前，这里先替你保存一小片空白。', source: 'copy' },
        { id: 'empty-world-3', text: '第一枚 token 被接入时，这个空间会拥有自己的第一束光。', source: 'copy' },
      ],
      you: '你',
      portraitEyebrow: 'Mint Portrait',
      partnersEyebrow: 'Companions',
      partnersTitle: '我的伙伴',
      notesEyebrow: 'Field Notes',
      notesTitle: '灵境杂记',
      share: '保存分享图',
      invite: '邀请新伙伴',
      personalityPrefix: '人格标签',
      waitingPartner: '等待第一位伙伴',
      shareFileName: 'whatmint-mint-space.png',
      shareMotto: '每一次相遇，都会让这个空间变得不同。',
      partnerDetailTitle: '伙伴详情',
      currentExperienceEyebrow: 'Experience',
      currentExperienceTitle: '当前体验',
      currentExperienceBody: '这位伙伴被触碰时，会优先打开你设置的默认内容；如果暂时没有设置，就继续使用官方默认体验。',
      tokenEyebrow: 'Object Token',
      tokenTitle: '实体凭证',
      tokenBody: 'Token 代表这个实体进入 Mint Space 的资格。请只在需要维护、转赠或重新接入时使用。',
      relationManageEyebrow: 'Relation',
      relationManageTitle: '关系管理',
      relationManageBody: '转赠会把这位伙伴交给另一个账号；解绑后，token 可以被重新接入新的 Mint Space。',
      addPartner: '接入新伙伴',
      prevPartner: '查看上一位伙伴',
      nextPartner: '查看下一位伙伴',
      backToSpace: '回到 Mint Space',
      partnerMissingTitle: '没有找到这位伙伴',
      partnerMissingBody: '它可能已经解绑、转赠，或不属于当前登录账号。',
      profileErrorTitle: 'Mint Space 暂时没有同步成功',
      profileError: 'Mint Space 需要通过 OS 聚合你的伙伴、空间人格和杂记。现在同步失败，请稍后重试。',
      retry: '重新同步',
    },
    instances: {
      empty: '暂无已绑定实体 IP',
      type: '实体 IP',
      unbind: '解绑',
      token: 'Token',
      defaultContent: '默认内容',
      contentId: (id: string) => `ID: ${id}...`,
      contentIdPlaceholder: '输入内容 ID',
      save: '保存',
      cancel: '取消',
      setSuggested: '设为带入内容',
      edit: '修改',
      transfer: '一键转赠',
      transferPlaceholder: '对方账号',
      transferAction: '转赠',
    },
    confirms: {
      unbind: '解绑后，这个 token 可被重新绑定到其他账号。确认要解绑这个 IP 实体吗？',
      transfer: (username: string) => `确认把这个 IP 实体转赠给「${username}」吗？转赠后你将失去它的管理权限。`,
    },
  },
};
