export const userCopy = {
  login: {
    title: 'whatmint',
    tabs: {
      login: '账户登录',
      register: '注册',
    },
    fields: {
      username: '用户名',
      password: '密码',
      confirmPassword: '确认密码',
    },
    actions: {
      login: '登录',
      loginLoading: '登录中...',
      register: '注册',
      registerLoading: '注册中...',
    },
    agreement: {
      prefix: '我已阅读并同意',
      disclaimer: '免责声明',
      and: '和',
      privacy: '隐私政策',
    },
    errors: {
      loginRequiredFields: '请填写用户名和密码',
      registerRequiredFields: '请填写所有字段',
      passwordMismatch: '两次密码不一致',
      passwordTooShort: '密码至少4位',
      loginFailed: '登录失败',
      registerFailed: '注册失败',
    },
  },
  account: {
    loginRequiredToast: '请先登录或注册后再进入账户设置',
    eyebrow: 'Account',
    title: '账户设置',
    intro: '这里只保留账号资料与安全设置；实体资产已经拆到独立的“我的资产”模块。',
    loading: '加载中...',
    creatorAccount: '创作者账号',
    normalAccount: '普通账号',
    password: {
      title: '修改密码',
      intro: '为了保护私有内容和资产管理权限，建议定期更新密码。',
      current: '当前密码',
      next: '新密码',
      confirm: '确认新密码',
      save: '保存新密码',
      required: '请填写所有密码字段',
      mismatch: '两次输入的新密码不一致',
      success: '密码修改成功',
      failed: '修改失败，请稍后再试',
    },
  },
  appeal: {
    eyebrow: 'Appeal',
    title: '订单号申诉解绑',
    intro: '如果 token 在运输中泄露并被抢先绑定，可在一个月内提交外部订单号，官方人工核验后处理解绑。',
    fields: {
      orderNo: '外部订单号',
      orderNoPlaceholder: '例如 WM20260713ABCD1234',
      token: 'token（可选）',
      tokenPlaceholder: '如果你手上有 token，可以一起提交',
      reason: '说明（可选）',
      reasonPlaceholder: '简单说明问题，例如 token 疑似运输途中泄露',
    },
    actions: {
      submit: '提交申诉',
      submitting: '提交中...',
    },
    messages: {
      orderRequired: '请输入外部订单号',
      submitted: '申诉已提交，官方会人工核验并处理解绑',
      toastSubmitted: '申诉已提交',
    },
  },
  wishlist: {
    removedToast: '已移出心愿单',
    externalPurchaseToast: (name: string) => `请在官方外部渠道购买「${name}」，收到 token 后到“我的资产”绑定实体。`,
    eyebrow: 'Wishlist',
    title: '心愿单',
    intro: '这里单独记录你想要的实体 IP，不再和商城混在同一个页面里。',
    emptyTitle: '心愿单还是空的',
    emptyBody: '去商城看看有没有想被做成实体的小狗。',
    goShop: '去商城',
    defaultContent: (title: string) => `已记录默认内容：${title}`,
    noDefaultContent: '未指定默认内容',
    externalPurchase: '去外部购买',
    remove: '移除',
  },
  assets: {
    galleryTypeEntity: '情绪 IP',
    unnamedIp: '未命名 IP',
    entityAsset: '实体资产',
    officialDefault: '官方默认内容',
    galleryTypeSticker: '日常贴纸',
    stickerTitle: '日常贴纸',
    stickerSubtitle: '连续小世界',
    waitingContent: '等待内容发布',
    tokenMissing: '未生成',
    toasts: {
      entityBoundDefaultSet: '实体已绑定，并写入当前内容为默认内容',
      entityBoundDefaultLater: '实体已绑定，默认内容需要稍后手动设置',
      unbound: '已解绑，token 可以重新绑定到其他账号',
      unbindFailed: '解绑失败',
      stickerRemoved: '贴纸已从展馆移出，token 可重新绑定',
      stickerRemoveFailed: '解除失败',
      tokenCopied: 'token 已复制',
      transferTargetRequired: '请输入接收方账号',
      transferSuccess: '转赠成功',
      transferFailed: '转赠失败',
      contentIdRequired: '请输入内容 ID',
      defaultUpdated: '默认内容已更新',
      updateFailed: '更新失败',
    },
    bind: {
      emptySmart: '请输入实体或贴纸 token',
      entitySuccessMuseum: '实体资产绑定成功，已经放入你的展馆',
      stickerAlreadyMuseum: '这个日常贴纸已经在你的展馆里',
      stickerSuccessMuseum: '日常贴纸绑定成功，已经放入你的展馆',
      failed: '绑定失败，请确认 token 是否正确',
      entityEmpty: '请输入实体 token',
      entitySuccess: '实体绑定成功',
      stickerEmpty: '请输入日常贴纸 token',
      stickerAlready: '这个贴纸已经在你的展馆里',
      stickerSuccess: '日常贴纸绑定成功',
    },
    hero: {
      eyebrow: 'My Museum',
      title: '我的资产展馆',
      intro: '这里收藏你拥有的实体 IP 和日常贴纸。实体 IP 负责关系与情绪表达，日常贴纸负责把普通物品变成可以随时推开的门。',
      bindNew: '绑定新资产',
      bindHint: '收到官方 token 后，从这里把实体放进展馆。',
      countLabel: '件展品',
      countDetail: (entities: number, stickers: number) => `${entities} 个 IP 实体 · ${stickers} 个日常贴纸`,
    },
    loginGuide: {
      title: '需要先登录或注册',
      body: '资产绑定、默认内容修改、转赠和贴纸归属都属于账号资产操作。请先登录，然后回到这里继续绑定。',
      tokenHint: '当前链接带有 token，登录后可重新打开链接，或复制 token 后在本页手动绑定。',
      backHome: '回到首页登录',
    },
    loading: '正在布置展馆...',
    bindCard: {
      eyebrow: 'Bind Token',
      title: '把新实体放进展馆',
      intro: '输入官方发放的 128 位 token。可以智能识别实体 IP 或日常贴纸；如果你很确定类型，也可以使用单独按钮。',
      placeholder: '输入实体或日常贴纸 token',
      smartBind: '智能绑定',
      entityOnly: '仅绑定实体 IP',
      stickerOnly: '仅绑定日常贴纸',
    },
    defaultHint: {
      title: '已带入一个内容 ID',
      body: '绑定实体后，可以在实体展品卡里一键把它设为默认播放内容。',
    },
    tabs: {
      gallery: '我的展馆',
      entities: '实体 IP',
      stickers: '日常贴纸',
      purchases: '购买记录',
    },
    emptyGallery: {
      title: '展馆还空着',
      body: '绑定一个实体 IP 或日常贴纸 token 后，它会出现在这里。',
      action: '去绑定 token',
    },
    entities: {
      empty: '暂无已绑定实体 IP',
      type: '实体 IP',
      unbind: '解绑',
      defaultContent: '默认内容',
      contentIdPlaceholder: '输入内容 ID',
      save: '保存',
      cancel: '取消',
      setSuggested: '设为带入内容',
      edit: '修改',
      transfer: '一键转赠',
      transferPlaceholder: '对方账号',
      transferAction: '转赠',
    },
    stickers: {
      empty: '暂无已绑定日常贴纸',
      type: '日常贴纸',
      todayContent: '今日内容',
      preview: '碰一下预览',
      copyToken: '复制 token',
      remove: '移出展馆',
    },
    purchases: {
      title: '购买记录',
      intro: '购买会迁移到外部平台完成。这里仅保留历史平台内记录和资产关系。',
      empty: '暂无购买记录',
      fallbackIp: 'IP',
      orderNo: (orderNo: string) => `订单号：${orderNo}`,
      shipped: '已发货',
      completed: '已完成',
      pending: '待发货',
    },
  },
};
