export const mintStudioProfiles = {
  'daily-sticker': {
    code: 'daily-sticker',
    name: '日常慢故事',
    appType: 'state',
    route: '/sticker',
    studioTitle: '慢故事贴纸铸造台',
    objectFallback: '这枚会讲慢故事的贴纸',
    introMessages: ['慢故事贴纸已识别。'],
    creationModes: [
      { code: 'open_app', label: '查看今日内容', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  'answer-book': {
    code: 'answer-book',
    name: '答案之书',
    appType: 'state',
    route: '/answer',
    studioTitle: '答案之书铸造台',
    objectFallback: '这枚会回答当下的贴纸',
    introMessages: ['答案之书已识别。'],
    creationModes: [
      { code: 'open_app', label: '获取答案', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  moment: {
    code: 'moment',
    name: '纪念瞬间',
    appType: 'meaning',
    route: '/moment',
    studioTitle: '纪念瞬间铸造台',
    objectFallback: '这枚保存瞬间的贴纸',
    introMessages: ['纪念瞬间已识别。'],
    creationModes: [
      { code: 'open_app', label: '打开这个瞬间', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
    studioFlow: {
      kind: 'guided',
      submitAction: 'save_moment_by_token',
      steps: [
        {
          id: 'title',
          type: 'text',
          answerKey: 'title',
          prompt: '给这一刻取个名字。',
          placeholder: '这一刻叫什么？',
          required: true,
        },
        {
          id: 'place',
          type: 'text',
          answerKey: 'place',
          prompt: '它发生在哪里？',
          placeholder: '发生在哪里？可直接发送跳过',
          optional: true,
        },
        {
          id: 'event_date',
          type: 'text',
          answerKey: 'eventDate',
          prompt: '是哪一天？',
          placeholder: '是哪一天？可直接发送跳过',
          optional: true,
        },
        {
          id: 'subtitle',
          type: 'text',
          answerKey: 'subtitle',
          prompt: '留一句话给这一刻。',
          placeholder: '写一句话。可直接发送跳过',
          optional: true,
        },
      ],
    },
  },
  'travel-trail': {
    code: 'travel-trail',
    name: '旅行轨迹',
    appType: 'meaning',
    route: '/trail',
    studioTitle: '旅行轨迹铸造台',
    objectFallback: '这件会移动的物品',
    introMessages: ['旅行轨迹已识别。'],
    creationModes: [
      { code: 'open_app', label: '写下下一站', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  check: {
    code: 'check',
    name: 'Check 检查',
    appType: 'behavior',
    route: '/check',
    studioTitle: 'Check 铸造台',
    objectFallback: '这件需要被检查的物品',
    introMessages: ['检查清单已识别。'],
    creationModes: [
      { code: 'open_app', label: '开始检查', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
};

export const mintStudioCopy = {
  moment: {
    blockTitle: '写给这一刻',
    fallbackTitle: '纪念瞬间',
    titleRequired: '给这一刻取个名字。',
    missing: '没有找到这个纪念瞬间。',
    notReady: '这个瞬间还没有准备好。',
  },
  library: {
    fallbackAssetBound: '已收藏资产',
    fallbackAssetUnbound: '未绑定物件',
    fallbackLabels: {
      'emotion-ip': '情绪 IP',
      content: '内容',
    },
  },
  entityRecipe: {
    tissuePuppy: '纸巾小狗',
    emotionIp: '情绪 IP',
    studioTitle: name => `${name}铸造台`,
    puppyStudioTitle: '纸巾小狗铸造台',
    currentContent: '当前内容',
    noContent: '暂无内容',
    useCurrent: '使用当前内容',
    keepCurrent: '保持当前内容',
    uploadVideo: '上传视频',
    collectAsset: '保存到展馆',
    completed: '已完成。',
    puppyCompleted: '纸巾小狗已完成。',
    officialPreview: '保留官方预览',
    customContent: '定制专属内容',
    puppyIntro: ['纸巾小狗已识别。', '选择当前内容，或上传专属视频。'],
    objectIntro: name => [`${name}已识别。`, '选择当前内容，或上传专属视频。'],
    puppyPrompt: '想让纸巾小狗递出哪一种内容？',
    objectPrompt: '选择这件物品要打开的内容。',
  },
  resolve: {
    tokenRequired: '请输入物件码。',
    tokenNotFound: '未找到物品。',
    tokenNotFoundHint: '请检查物件码。',
    failed: '打开失败。',
    retryHint: '请稍后重试。',
  },
  save: {
    failed: '保存失败。请稍后重试。',
  },
};
