export const mintStudioProfiles = {
  'earphone-girl': {
    code: 'earphone-girl',
    name: '耳机小姐',
    appType: 'meaning',
    route: '/earphone-girl',
    studioTitle: '耳机小姐故事空间',
    objectFallback: '这枚会带回故事的耳机贴纸',
    introMessages: ['耳机小姐已识别。'],
    creationModes: [
      { code: 'open_app', label: '听她讲故事', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  'answer-book': {
    code: 'answer-book',
    name: '答案之书',
    appType: 'state',
    route: '/answer',
    studioTitle: '答案之书铸造台',
    objectFallback: '这枚会回答当下的贴纸',
    introMessages: ['答案之书已识别。'],
    creationModes: [
      { code: 'open_app', label: '获取答案', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  moment: {
    code: 'moment',
    name: '纪念瞬间',
    appType: 'meaning',
    route: '/moment',
    studioTitle: '纪念瞬间铸造台',
    objectFallback: '这枚保存瞬间的贴纸',
    introMessages: ['纪念瞬间已识别。'],
    creationModes: [
      { code: 'open_app', label: '打开这个瞬间', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  'travel-trail': {
    code: 'travel-trail',
    name: '旅行轨迹',
    appType: 'meaning',
    route: '/trail',
    studioTitle: '旅行轨迹铸造台',
    objectFallback: '这件会移动的物品',
    introMessages: ['旅行轨迹已识别。'],
    creationModes: [
      { code: 'open_app', label: '写下下一站', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
  check: {
    code: 'check',
    name: 'Check 检查',
    appType: 'behavior',
    route: '/check',
    studioTitle: 'Check 铸造台',
    objectFallback: '这件需要被检查的物品',
    introMessages: ['检查清单已识别。'],
    creationModes: [
      { code: 'open_app', label: '开始检查', tone: 'primary' },
      { code: 'collect_asset', label: '保存到展馆', tone: 'quiet', requiresAuth: true },
    ],
  },
};

export const mintStudioCopy = {
  library: {
    fallbackLabels: {
      'emotion-ip': '情绪 IP',
      'earphone-girl': '耳机小姐',
      content: '内容',
    },
  },
  entityRecipe: {
    tissuePuppy: '纸巾小狗',
    emotionIp: '情绪 IP',
    studioTitle: name => `${name}铸造台`,
    puppyStudioTitle: '纸巾小狗铸造台',
    currentContent: '当前内容',
    noContent: '暂无内容',
    previewCurrent: '预览当前内容',
    previewObject: '查看物件',
    collectAsset: '保存到展馆',
    completed: '已完成。',
    puppyCompleted: '纸巾小狗已完成。',
    puppyIntro: ['纸巾小狗已识别。', '会按它的内容定义继续创作。'],
    objectIntro: name => [`${name}已识别。`, '会按它的内容定义继续创作。'],
    puppyPrompt: '想让纸巾小狗递出哪一种内容？',
    objectPrompt: '选择这件物品要打开的内容。',
  },
  resolve: {
    tokenRequired: '请输入物件码。',
    tokenNotFound: '未找到物品。',
    tokenNotFoundHint: '请检查物件码。',
    failed: '打开失败。',
    retryHint: '请稍后重试。',
  },
  save: {
    failed: '保存失败。请稍后重试。',
  },
  contentVersion: {
    appName: '内容协议',
    compactToken: 'CONTENT',
    untitled: '未命名内容',
    bodyLabel: '正文',
    reviseTitle: title => `修改「${title}」`,
    extendTitle: title => `续写「${title}」`,
    reviseIntro: ['我们会先保存一个新版草稿，确认后再发布，不直接覆盖原内容。'],
    extendIntro: ['续写会保留原内容，并把新的段落接到后面。'],
    reviseMode: '修改内容',
    extendMode: '续写内容',
    revisePrompt: '你想调整哪里？',
    extendPrompt: '你想往后写什么？',
    revisePlaceholder: '例如：语气更克制，删掉过于直白的句子',
    extendPlaceholder: '例如：让她继续写一次去草原找纸巾小狗的故事',
    reviseBodyPrompt: field => `如果你已经想好了，可以直接写新版${field}；也可以发送“跳过”，只记录修改意图。`,
    extendBodyPrompt: field => `写下要续上的${field}；也可以发送“跳过”，先只保存续写方向。`,
    bodyPlaceholder: '输入正文，或发送“跳过”',
    revisionBlockTitle: '修改草稿',
    extensionBlockTitle: '续写',
    published: '新版内容已发布。',
  },
  definitionFlow: {
    defaultUnitLabel: '第 {index} 段',
    continuePrompt: '这一段已经准备好。要继续上传下一段，还是完成铸造？',
    appendLabel: '继续上传下一段',
    appendDescription: '继续添加一段插画和声音。',
    publishLabel: '完成铸造',
    publishDescription: '生成内容资产，之后可在内容详情页预览和修改。',
    resourceFallback: '按内容定义补充资源',
    chooseContentDefinition: '这枚物件可以创作这些内容。先选一种内容形态，我们再按定义继续。',
    continueByDefinition: '按内容定义继续创作。',
    resourcePlanPrompt: resourceCopy => `最后确认资源方向：${resourceCopy}。如果暂时没有正式素材，可以写“先用占位”。`,
    resourcePlanPlaceholder: '例如：先用占位插画，语音后补',
    uploadResourcePrompt: (unitLabel, index, label) => `${unitLabel.replace('{index}', String(index))}：上传${label}。`,
  },
};
