export const CONTENT_DEFINITIONS = [
  {
    id: 'cntdef_earphone_girl_periodic_story',
    code: 'earphone-girl-periodic-story',
    name: '耳机小姐故事',
    description: '耳机小姐按实例队列讲述的一段主故事。',
    relationRole: 'default_story',
    isPrimary: 1,
    sortOrder: 0,
    authoringSchema: {
      authoringProtocol: {
        createFlow: 'repeatable_resource_sequence',
        unitLabel: '第 {index} 段故事',
        continuePrompt: '这一段故事已经收好。要继续上传下一段，还是完成铸造？',
        appendLabel: '继续上传下一段',
        publishLabel: '完成铸造',
      },
      contentShape: {
        unit: 'story_page',
        repeatable: true,
        minUnits: 1,
        slots: [
          { key: 'illustration', role: 'story_visual', type: 'image', label: '插画', required: true, accept: 'image/*' },
          { key: 'audio', role: 'story_voice', type: 'audio', label: '语音', required: true, accept: 'audio/*' },
        ],
      },
      fields: [
        { key: 'title', label: '故事标题', prompt: '先给这段故事取一个轻轻的名字。', required: true },
        { key: 'lead', label: '开场句', prompt: '写一句她刚回来时会说的话。', required: true },
        { key: 'body', label: '故事正文', prompt: '写下她遇见了什么，以及这件事留下的感觉。', required: true },
        { key: 'mood', label: '情绪标签', prompt: '用一个词标记这段故事的气味。', required: true },
        { key: 'voiceoverText', label: '旁白文案', prompt: '写成耳机小姐会亲口说出的声音。', required: true },
        { key: 'cta', label: '可选入口', prompt: '如果她提到了某个 IP，补一个进入它空间的入口。', required: false },
      ],
      resourceRequirements: [
        { role: 'story_visual', type: 'image', label: '故事插画', required: true, maxCount: 1 },
        { role: 'story_voice', type: 'audio', label: '故事语音', required: false, maxCount: 1 },
        { role: 'story_bgm', type: 'audio', label: '氛围音乐', required: false, maxCount: 1 },
      ],
    },
    template: { renderer: 'story_audio_card_v1', layout: 'single_visual_with_caption' },
    extra: { toneRule: '像她真的遇见了一件事，再回来轻轻讲给朋友听。' },
  },
  {
    id: 'cntdef_earphone_girl_crossover_invite',
    code: 'earphone-girl-crossover-invite',
    name: '耳机小姐联动邀请',
    description: '耳机小姐遇见其他 IP 后带回来的联动入口。',
    relationRole: 'crossover_preview',
    isPrimary: 0,
    sortOrder: 10,
    authoringSchema: {
      fields: [
        { key: 'title', label: '联动标题', prompt: '写出她刚从谁那里回来。', required: true },
        { key: 'sceneText', label: '联动画面', prompt: '写一幕她和那个 IP 相处的画面。', required: true },
        { key: 'relationLabel', label: '关系标签', prompt: '用一句克制的话说明他们的关系。', required: true },
        { key: 'entryLabel', label: '入口按钮', prompt: '给进入对方空间的按钮取名。', required: true },
      ],
      resourceRequirements: [
        { role: 'crossover_visual', type: 'image', label: '联动插画', required: true, maxCount: 1 },
        { role: 'crossover_music', type: 'audio', label: '联动音乐', required: false, maxCount: 1 },
      ],
    },
    template: { renderer: 'crossover_gateway_card_v1', layout: 'illustration_with_entry_button' },
    extra: { toneRule: '分享遇见，不做推销。' },
  },
  {
    id: 'cntdef_earphone_girl_memory_story',
    code: 'earphone-girl-memory-story',
    name: '耳机小姐记忆故事',
    description: '耳机小姐保存已经发生过的故事片段。',
    relationRole: 'memory_archive',
    isPrimary: 0,
    sortOrder: 20,
    authoringSchema: {
      fields: [
        { key: 'title', label: '记忆标题', prompt: '给这个发生过的故事取名。', required: true },
        { key: 'summary', label: '记忆摘要', prompt: '用一句话说明它为什么值得留下。', required: true },
        { key: 'storyMoment', label: '记忆片段', prompt: '写下那一刻真正发生了什么。', required: true },
        { key: 'relatedIpDefinitionIds', label: '关联 IP', prompt: '如果这段记忆属于某个朋友，把它记下来。', required: false },
      ],
      resourceRequirements: [
        { role: 'memory_visual', type: 'image', label: '记忆插画', required: false, maxCount: 1 },
        { role: 'memory_voice', type: 'audio', label: '记忆语音', required: false, maxCount: 1 },
      ],
    },
    template: { renderer: 'memory_story_note_v1', layout: 'scrapbook_note' },
    extra: { toneRule: '这是发生过的故事，不是连续日记。' },
  },
];

export const STORY_CONTENTS = [
  {
    id: 'cntinst_earphone_girl_story_001',
    title: '她把一条小路听成了地图',
    summary: '耳机小姐第一次推开 WhatMint 世界的门。',
    visual: '/earphone-girl/story-01.svg',
    payload: {
      queueKey: 'official-main-sequence',
      sequenceOrder: 1,
      title: '她把一条小路听成了地图',
      lead: '耳机小姐今天出门很早。',
      body: '她说，有些地方不是靠导航找到的，是靠一个很轻的声音。风经过贴纸边缘，像有人翻开一页新的手账。她站在那里听了很久，确认这不是迷路，是世界在邀请她往前走一点。',
      mood: '出发',
      voiceoverText: '我今天听见一条小路，它没有催我，只是轻轻往前亮了一下。',
      cta: null,
    },
  },
  {
    id: 'cntinst_earphone_girl_story_002',
    title: '她在草地边遇见纸巾小狗',
    summary: '耳机小姐把纸巾小狗的温柔带回来了。',
    visual: '/earphone-girl/story-02.svg',
    payload: {
      queueKey: 'official-main-sequence',
      sequenceOrder: 2,
      title: '她在草地边遇见纸巾小狗',
      lead: '耳机小姐今天去看了纸巾小狗。',
      body: '草叶被风吹得有一点歪。纸巾小狗没有说很多话，只把口袋里的纸巾叠整齐。耳机小姐坐在旁边，听见它把“没关系”藏进每一次递出的动作里。',
      mood: '柔软',
      voiceoverText: '我今天见到纸巾小狗了。它还是那样，安静地照顾着每一个来不及说出口的心情。',
      cta: {
        label: '进入纸巾小狗空间',
        targetIpDefinitionId: 'ipdef_tissue_puppy',
        targetType: 'official_ip_example',
      },
    },
  },
  {
    id: 'cntinst_earphone_girl_story_003',
    title: '她向答案之书借了一句安静',
    summary: '耳机小姐遇见答案之书，学会把答案留白。',
    visual: '/earphone-girl/story-03.svg',
    payload: {
      queueKey: 'official-main-sequence',
      sequenceOrder: 3,
      title: '她向答案之书借了一句安静',
      lead: '耳机小姐路过一间很小的书房。',
      body: '答案之书没有马上回答她。它只是把页面停在一行空白上。耳机小姐突然明白，有些答案不是被说出来的，是等人终于愿意慢下来时，自己浮上来的。',
      mood: '克制',
      voiceoverText: '答案之书今天没有给我答案。它只给了我一点安静，我觉得刚刚好。',
      cta: {
        label: '看看答案之书',
        targetIpDefinitionId: 'ipdef_answer_book',
        targetType: 'official_ip_example',
      },
    },
  },
  {
    id: 'cntinst_earphone_girl_story_004',
    title: '她帮旅行检查单收起一阵风',
    summary: '耳机小姐看见旅行检查单把出发前的慌乱整理好。',
    visual: '/earphone-girl/story-04.svg',
    payload: {
      queueKey: 'official-main-sequence',
      sequenceOrder: 4,
      title: '她帮旅行检查单收起一阵风',
      lead: '耳机小姐今天遇见了旅行检查单。',
      body: '它把一件件小事排好：钥匙、耳机、证件、还有那一点说不出口的紧张。耳机小姐在旁边听着，觉得出发不是离开生活，而是把生活轻轻折好，放进口袋。',
      mood: '出发前',
      voiceoverText: '旅行检查单今天很认真。它说，真正的安心不是不出错，是出门前有人陪你再看一眼。',
      cta: {
        label: '看看旅行检查单',
        targetIpDefinitionId: 'ipdef_travel_checklist',
        targetType: 'official_ip_example',
      },
    },
  },
  {
    id: 'cntinst_earphone_girl_story_005',
    title: '她把黄昏留在耳机里',
    summary: '耳机小姐带回一段没有目的地的声音。',
    visual: '/earphone-girl/story-05.svg',
    payload: {
      queueKey: 'official-main-sequence',
      sequenceOrder: 5,
      title: '她把黄昏留在耳机里',
      lead: '耳机小姐今天没有遇见谁。',
      body: '她只是坐在一盏灯慢慢亮起来的地方，听城市把白天收好。不是每一次旅行都要带回新朋友，有时候，带回一点安静，也算很珍贵的收获。',
      mood: '安静',
      voiceoverText: '今天我没有特别想说的大事。只是觉得，如果你也刚好累了，可以把世界调低一点。',
      cta: null,
    },
  },
];

export const CROSSOVER_CONTENTS = [
  {
    id: 'cntinst_earphone_girl_crossover_tissue_puppy_001',
    definitionId: 'cntdef_earphone_girl_crossover_invite',
    relationRole: 'crossover_preview',
    resourceRole: 'crossover_visual',
    title: '她刚从纸巾小狗那里回来',
    summary: '耳机小姐带回纸巾小狗的草地邀请。',
    visual: '/earphone-girl/crossover-tissue-puppy.svg',
    payload: {
      title: '她刚从纸巾小狗那里回来',
      sceneText: '草地边有一点风。纸巾小狗把今天收到的温柔都叠好，像怕谁突然需要一张纸。',
      relationLabel: '会互相惦记的好朋友',
      linkedIpDefinitionId: 'ipdef_tissue_puppy',
      entryLabel: '进入纸巾小狗空间',
      entryTargetIpDefinitionId: 'ipdef_tissue_puppy',
      entryTargetType: 'official_ip_example',
    },
  },
];

export const MEMORY_CONTENTS = [
  {
    id: 'cntinst_earphone_girl_memory_first_trip_001',
    definitionId: 'cntdef_earphone_girl_memory_story',
    relationRole: 'memory_archive',
    resourceRole: 'memory_visual',
    title: '第一次听见这座小小世界',
    summary: '耳机小姐把第一次出发存成一张记忆便签。',
    visual: '/earphone-girl/memory-first-trip.svg',
    payload: {
      title: '第一次听见这座小小世界',
      summary: '一次关于小路、风声和新朋友的开始。',
      storyMoment: '她发现 WhatMint 世界不是一张地图，而是一群愿意被慢慢认识的朋友。',
      sourceEventType: 'official.seed.memory',
      relatedIpDefinitionIds: ['ipdef_earphone_girl'],
    },
  },
];
